#pragma once

/* GENERATED by tools/gen_winmm_forwarders.ps1 - do not edit by hand. */
/* Forwards every named export of the real winmm.dll via assembly thunks
 * (see winmm_forward.s / winmm.def). */

/* Loads the real system winmm.dll and resolves every forwarded pointer. */
void winmm_forward_init(void);

