# GENERATED by tools/gen_winmm_forwarders.ps1 - do not edit by hand.
# One transparent tail-jump trampoline per forwarded winmm export.
# jmp *ptr_NAME(%rip) transfers control through the resolved real
# function pointer without touching the stack or any register, so the
# original caller's arguments and return address pass through untouched
# regardless of the target function's real signature.
    .text
    .globl auxGetDevCapsA
    .p2align 4, 0x90
auxGetDevCapsA:
    jmp *ptr_auxGetDevCapsA(%rip)

    .globl auxGetDevCapsW
    .p2align 4, 0x90
auxGetDevCapsW:
    jmp *ptr_auxGetDevCapsW(%rip)

    .globl auxGetNumDevs
    .p2align 4, 0x90
auxGetNumDevs:
    jmp *ptr_auxGetNumDevs(%rip)

    .globl auxGetVolume
    .p2align 4, 0x90
auxGetVolume:
    jmp *ptr_auxGetVolume(%rip)

    .globl auxOutMessage
    .p2align 4, 0x90
auxOutMessage:
    jmp *ptr_auxOutMessage(%rip)

    .globl auxSetVolume
    .p2align 4, 0x90
auxSetVolume:
    jmp *ptr_auxSetVolume(%rip)

    .globl CloseDriver
    .p2align 4, 0x90
CloseDriver:
    jmp *ptr_CloseDriver(%rip)

    .globl DefDriverProc
    .p2align 4, 0x90
DefDriverProc:
    jmp *ptr_DefDriverProc(%rip)

    .globl DriverCallback
    .p2align 4, 0x90
DriverCallback:
    jmp *ptr_DriverCallback(%rip)

    .globl DrvGetModuleHandle
    .p2align 4, 0x90
DrvGetModuleHandle:
    jmp *ptr_DrvGetModuleHandle(%rip)

    .globl GetDriverModuleHandle
    .p2align 4, 0x90
GetDriverModuleHandle:
    jmp *ptr_GetDriverModuleHandle(%rip)

    .globl joyConfigChanged
    .p2align 4, 0x90
joyConfigChanged:
    jmp *ptr_joyConfigChanged(%rip)

    .globl joyGetDevCapsA
    .p2align 4, 0x90
joyGetDevCapsA:
    jmp *ptr_joyGetDevCapsA(%rip)

    .globl joyGetDevCapsW
    .p2align 4, 0x90
joyGetDevCapsW:
    jmp *ptr_joyGetDevCapsW(%rip)

    .globl joyGetNumDevs
    .p2align 4, 0x90
joyGetNumDevs:
    jmp *ptr_joyGetNumDevs(%rip)

    .globl joyGetPos
    .p2align 4, 0x90
joyGetPos:
    jmp *ptr_joyGetPos(%rip)

    .globl joyGetPosEx
    .p2align 4, 0x90
joyGetPosEx:
    jmp *ptr_joyGetPosEx(%rip)

    .globl joyGetThreshold
    .p2align 4, 0x90
joyGetThreshold:
    jmp *ptr_joyGetThreshold(%rip)

    .globl joyReleaseCapture
    .p2align 4, 0x90
joyReleaseCapture:
    jmp *ptr_joyReleaseCapture(%rip)

    .globl joySetCapture
    .p2align 4, 0x90
joySetCapture:
    jmp *ptr_joySetCapture(%rip)

    .globl joySetThreshold
    .p2align 4, 0x90
joySetThreshold:
    jmp *ptr_joySetThreshold(%rip)

    .globl mciDriverNotify
    .p2align 4, 0x90
mciDriverNotify:
    jmp *ptr_mciDriverNotify(%rip)

    .globl mciDriverYield
    .p2align 4, 0x90
mciDriverYield:
    jmp *ptr_mciDriverYield(%rip)

    .globl mciExecute
    .p2align 4, 0x90
mciExecute:
    jmp *ptr_mciExecute(%rip)

    .globl mciFreeCommandResource
    .p2align 4, 0x90
mciFreeCommandResource:
    jmp *ptr_mciFreeCommandResource(%rip)

    .globl mciGetCreatorTask
    .p2align 4, 0x90
mciGetCreatorTask:
    jmp *ptr_mciGetCreatorTask(%rip)

    .globl mciGetDeviceIDA
    .p2align 4, 0x90
mciGetDeviceIDA:
    jmp *ptr_mciGetDeviceIDA(%rip)

    .globl mciGetDeviceIDFromElementIDA
    .p2align 4, 0x90
mciGetDeviceIDFromElementIDA:
    jmp *ptr_mciGetDeviceIDFromElementIDA(%rip)

    .globl mciGetDeviceIDFromElementIDW
    .p2align 4, 0x90
mciGetDeviceIDFromElementIDW:
    jmp *ptr_mciGetDeviceIDFromElementIDW(%rip)

    .globl mciGetDeviceIDW
    .p2align 4, 0x90
mciGetDeviceIDW:
    jmp *ptr_mciGetDeviceIDW(%rip)

    .globl mciGetDriverData
    .p2align 4, 0x90
mciGetDriverData:
    jmp *ptr_mciGetDriverData(%rip)

    .globl mciGetErrorStringA
    .p2align 4, 0x90
mciGetErrorStringA:
    jmp *ptr_mciGetErrorStringA(%rip)

    .globl mciGetErrorStringW
    .p2align 4, 0x90
mciGetErrorStringW:
    jmp *ptr_mciGetErrorStringW(%rip)

    .globl mciGetYieldProc
    .p2align 4, 0x90
mciGetYieldProc:
    jmp *ptr_mciGetYieldProc(%rip)

    .globl mciLoadCommandResource
    .p2align 4, 0x90
mciLoadCommandResource:
    jmp *ptr_mciLoadCommandResource(%rip)

    .globl mciSendCommandA
    .p2align 4, 0x90
mciSendCommandA:
    jmp *ptr_mciSendCommandA(%rip)

    .globl mciSendCommandW
    .p2align 4, 0x90
mciSendCommandW:
    jmp *ptr_mciSendCommandW(%rip)

    .globl mciSendStringA
    .p2align 4, 0x90
mciSendStringA:
    jmp *ptr_mciSendStringA(%rip)

    .globl mciSendStringW
    .p2align 4, 0x90
mciSendStringW:
    jmp *ptr_mciSendStringW(%rip)

    .globl mciSetDriverData
    .p2align 4, 0x90
mciSetDriverData:
    jmp *ptr_mciSetDriverData(%rip)

    .globl mciSetYieldProc
    .p2align 4, 0x90
mciSetYieldProc:
    jmp *ptr_mciSetYieldProc(%rip)

    .globl midiConnect
    .p2align 4, 0x90
midiConnect:
    jmp *ptr_midiConnect(%rip)

    .globl midiDisconnect
    .p2align 4, 0x90
midiDisconnect:
    jmp *ptr_midiDisconnect(%rip)

    .globl midiInAddBuffer
    .p2align 4, 0x90
midiInAddBuffer:
    jmp *ptr_midiInAddBuffer(%rip)

    .globl midiInClose
    .p2align 4, 0x90
midiInClose:
    jmp *ptr_midiInClose(%rip)

    .globl midiInGetDevCapsA
    .p2align 4, 0x90
midiInGetDevCapsA:
    jmp *ptr_midiInGetDevCapsA(%rip)

    .globl midiInGetDevCapsW
    .p2align 4, 0x90
midiInGetDevCapsW:
    jmp *ptr_midiInGetDevCapsW(%rip)

    .globl midiInGetErrorTextA
    .p2align 4, 0x90
midiInGetErrorTextA:
    jmp *ptr_midiInGetErrorTextA(%rip)

    .globl midiInGetErrorTextW
    .p2align 4, 0x90
midiInGetErrorTextW:
    jmp *ptr_midiInGetErrorTextW(%rip)

    .globl midiInGetID
    .p2align 4, 0x90
midiInGetID:
    jmp *ptr_midiInGetID(%rip)

    .globl midiInGetNumDevs
    .p2align 4, 0x90
midiInGetNumDevs:
    jmp *ptr_midiInGetNumDevs(%rip)

    .globl midiInMessage
    .p2align 4, 0x90
midiInMessage:
    jmp *ptr_midiInMessage(%rip)

    .globl midiInOpen
    .p2align 4, 0x90
midiInOpen:
    jmp *ptr_midiInOpen(%rip)

    .globl midiInPrepareHeader
    .p2align 4, 0x90
midiInPrepareHeader:
    jmp *ptr_midiInPrepareHeader(%rip)

    .globl midiInReset
    .p2align 4, 0x90
midiInReset:
    jmp *ptr_midiInReset(%rip)

    .globl midiInStart
    .p2align 4, 0x90
midiInStart:
    jmp *ptr_midiInStart(%rip)

    .globl midiInStop
    .p2align 4, 0x90
midiInStop:
    jmp *ptr_midiInStop(%rip)

    .globl midiInUnprepareHeader
    .p2align 4, 0x90
midiInUnprepareHeader:
    jmp *ptr_midiInUnprepareHeader(%rip)

    .globl midiOutCacheDrumPatches
    .p2align 4, 0x90
midiOutCacheDrumPatches:
    jmp *ptr_midiOutCacheDrumPatches(%rip)

    .globl midiOutCachePatches
    .p2align 4, 0x90
midiOutCachePatches:
    jmp *ptr_midiOutCachePatches(%rip)

    .globl midiOutClose
    .p2align 4, 0x90
midiOutClose:
    jmp *ptr_midiOutClose(%rip)

    .globl midiOutGetDevCapsA
    .p2align 4, 0x90
midiOutGetDevCapsA:
    jmp *ptr_midiOutGetDevCapsA(%rip)

    .globl midiOutGetDevCapsW
    .p2align 4, 0x90
midiOutGetDevCapsW:
    jmp *ptr_midiOutGetDevCapsW(%rip)

    .globl midiOutGetErrorTextA
    .p2align 4, 0x90
midiOutGetErrorTextA:
    jmp *ptr_midiOutGetErrorTextA(%rip)

    .globl midiOutGetErrorTextW
    .p2align 4, 0x90
midiOutGetErrorTextW:
    jmp *ptr_midiOutGetErrorTextW(%rip)

    .globl midiOutGetID
    .p2align 4, 0x90
midiOutGetID:
    jmp *ptr_midiOutGetID(%rip)

    .globl midiOutGetNumDevs
    .p2align 4, 0x90
midiOutGetNumDevs:
    jmp *ptr_midiOutGetNumDevs(%rip)

    .globl midiOutGetVolume
    .p2align 4, 0x90
midiOutGetVolume:
    jmp *ptr_midiOutGetVolume(%rip)

    .globl midiOutLongMsg
    .p2align 4, 0x90
midiOutLongMsg:
    jmp *ptr_midiOutLongMsg(%rip)

    .globl midiOutMessage
    .p2align 4, 0x90
midiOutMessage:
    jmp *ptr_midiOutMessage(%rip)

    .globl midiOutOpen
    .p2align 4, 0x90
midiOutOpen:
    jmp *ptr_midiOutOpen(%rip)

    .globl midiOutPrepareHeader
    .p2align 4, 0x90
midiOutPrepareHeader:
    jmp *ptr_midiOutPrepareHeader(%rip)

    .globl midiOutReset
    .p2align 4, 0x90
midiOutReset:
    jmp *ptr_midiOutReset(%rip)

    .globl midiOutSetVolume
    .p2align 4, 0x90
midiOutSetVolume:
    jmp *ptr_midiOutSetVolume(%rip)

    .globl midiOutShortMsg
    .p2align 4, 0x90
midiOutShortMsg:
    jmp *ptr_midiOutShortMsg(%rip)

    .globl midiOutUnprepareHeader
    .p2align 4, 0x90
midiOutUnprepareHeader:
    jmp *ptr_midiOutUnprepareHeader(%rip)

    .globl midiStreamClose
    .p2align 4, 0x90
midiStreamClose:
    jmp *ptr_midiStreamClose(%rip)

    .globl midiStreamOpen
    .p2align 4, 0x90
midiStreamOpen:
    jmp *ptr_midiStreamOpen(%rip)

    .globl midiStreamOut
    .p2align 4, 0x90
midiStreamOut:
    jmp *ptr_midiStreamOut(%rip)

    .globl midiStreamPause
    .p2align 4, 0x90
midiStreamPause:
    jmp *ptr_midiStreamPause(%rip)

    .globl midiStreamPosition
    .p2align 4, 0x90
midiStreamPosition:
    jmp *ptr_midiStreamPosition(%rip)

    .globl midiStreamProperty
    .p2align 4, 0x90
midiStreamProperty:
    jmp *ptr_midiStreamProperty(%rip)

    .globl midiStreamRestart
    .p2align 4, 0x90
midiStreamRestart:
    jmp *ptr_midiStreamRestart(%rip)

    .globl midiStreamStop
    .p2align 4, 0x90
midiStreamStop:
    jmp *ptr_midiStreamStop(%rip)

    .globl mixerClose
    .p2align 4, 0x90
mixerClose:
    jmp *ptr_mixerClose(%rip)

    .globl mixerGetControlDetailsA
    .p2align 4, 0x90
mixerGetControlDetailsA:
    jmp *ptr_mixerGetControlDetailsA(%rip)

    .globl mixerGetControlDetailsW
    .p2align 4, 0x90
mixerGetControlDetailsW:
    jmp *ptr_mixerGetControlDetailsW(%rip)

    .globl mixerGetDevCapsA
    .p2align 4, 0x90
mixerGetDevCapsA:
    jmp *ptr_mixerGetDevCapsA(%rip)

    .globl mixerGetDevCapsW
    .p2align 4, 0x90
mixerGetDevCapsW:
    jmp *ptr_mixerGetDevCapsW(%rip)

    .globl mixerGetID
    .p2align 4, 0x90
mixerGetID:
    jmp *ptr_mixerGetID(%rip)

    .globl mixerGetLineControlsA
    .p2align 4, 0x90
mixerGetLineControlsA:
    jmp *ptr_mixerGetLineControlsA(%rip)

    .globl mixerGetLineControlsW
    .p2align 4, 0x90
mixerGetLineControlsW:
    jmp *ptr_mixerGetLineControlsW(%rip)

    .globl mixerGetLineInfoA
    .p2align 4, 0x90
mixerGetLineInfoA:
    jmp *ptr_mixerGetLineInfoA(%rip)

    .globl mixerGetLineInfoW
    .p2align 4, 0x90
mixerGetLineInfoW:
    jmp *ptr_mixerGetLineInfoW(%rip)

    .globl mixerGetNumDevs
    .p2align 4, 0x90
mixerGetNumDevs:
    jmp *ptr_mixerGetNumDevs(%rip)

    .globl mixerMessage
    .p2align 4, 0x90
mixerMessage:
    jmp *ptr_mixerMessage(%rip)

    .globl mixerOpen
    .p2align 4, 0x90
mixerOpen:
    jmp *ptr_mixerOpen(%rip)

    .globl mixerSetControlDetails
    .p2align 4, 0x90
mixerSetControlDetails:
    jmp *ptr_mixerSetControlDetails(%rip)

    .globl mmDrvInstall
    .p2align 4, 0x90
mmDrvInstall:
    jmp *ptr_mmDrvInstall(%rip)

    .globl mmGetCurrentTask
    .p2align 4, 0x90
mmGetCurrentTask:
    jmp *ptr_mmGetCurrentTask(%rip)

    .globl mmioAdvance
    .p2align 4, 0x90
mmioAdvance:
    jmp *ptr_mmioAdvance(%rip)

    .globl mmioAscend
    .p2align 4, 0x90
mmioAscend:
    jmp *ptr_mmioAscend(%rip)

    .globl mmioClose
    .p2align 4, 0x90
mmioClose:
    jmp *ptr_mmioClose(%rip)

    .globl mmioCreateChunk
    .p2align 4, 0x90
mmioCreateChunk:
    jmp *ptr_mmioCreateChunk(%rip)

    .globl mmioDescend
    .p2align 4, 0x90
mmioDescend:
    jmp *ptr_mmioDescend(%rip)

    .globl mmioFlush
    .p2align 4, 0x90
mmioFlush:
    jmp *ptr_mmioFlush(%rip)

    .globl mmioGetInfo
    .p2align 4, 0x90
mmioGetInfo:
    jmp *ptr_mmioGetInfo(%rip)

    .globl mmioInstallIOProcA
    .p2align 4, 0x90
mmioInstallIOProcA:
    jmp *ptr_mmioInstallIOProcA(%rip)

    .globl mmioInstallIOProcW
    .p2align 4, 0x90
mmioInstallIOProcW:
    jmp *ptr_mmioInstallIOProcW(%rip)

    .globl mmioOpenA
    .p2align 4, 0x90
mmioOpenA:
    jmp *ptr_mmioOpenA(%rip)

    .globl mmioOpenW
    .p2align 4, 0x90
mmioOpenW:
    jmp *ptr_mmioOpenW(%rip)

    .globl mmioRead
    .p2align 4, 0x90
mmioRead:
    jmp *ptr_mmioRead(%rip)

    .globl mmioRenameA
    .p2align 4, 0x90
mmioRenameA:
    jmp *ptr_mmioRenameA(%rip)

    .globl mmioRenameW
    .p2align 4, 0x90
mmioRenameW:
    jmp *ptr_mmioRenameW(%rip)

    .globl mmioSeek
    .p2align 4, 0x90
mmioSeek:
    jmp *ptr_mmioSeek(%rip)

    .globl mmioSendMessage
    .p2align 4, 0x90
mmioSendMessage:
    jmp *ptr_mmioSendMessage(%rip)

    .globl mmioSetBuffer
    .p2align 4, 0x90
mmioSetBuffer:
    jmp *ptr_mmioSetBuffer(%rip)

    .globl mmioSetInfo
    .p2align 4, 0x90
mmioSetInfo:
    jmp *ptr_mmioSetInfo(%rip)

    .globl mmioStringToFOURCCA
    .p2align 4, 0x90
mmioStringToFOURCCA:
    jmp *ptr_mmioStringToFOURCCA(%rip)

    .globl mmioStringToFOURCCW
    .p2align 4, 0x90
mmioStringToFOURCCW:
    jmp *ptr_mmioStringToFOURCCW(%rip)

    .globl mmioWrite
    .p2align 4, 0x90
mmioWrite:
    jmp *ptr_mmioWrite(%rip)

    .globl mmsystemGetVersion
    .p2align 4, 0x90
mmsystemGetVersion:
    jmp *ptr_mmsystemGetVersion(%rip)

    .globl mmTaskBlock
    .p2align 4, 0x90
mmTaskBlock:
    jmp *ptr_mmTaskBlock(%rip)

    .globl mmTaskCreate
    .p2align 4, 0x90
mmTaskCreate:
    jmp *ptr_mmTaskCreate(%rip)

    .globl mmTaskSignal
    .p2align 4, 0x90
mmTaskSignal:
    jmp *ptr_mmTaskSignal(%rip)

    .globl mmTaskYield
    .p2align 4, 0x90
mmTaskYield:
    jmp *ptr_mmTaskYield(%rip)

    .globl OpenDriver
    .p2align 4, 0x90
OpenDriver:
    jmp *ptr_OpenDriver(%rip)

    .globl PlaySound
    .p2align 4, 0x90
PlaySound:
    jmp *ptr_PlaySound(%rip)

    .globl PlaySoundA
    .p2align 4, 0x90
PlaySoundA:
    jmp *ptr_PlaySoundA(%rip)

    .globl PlaySoundW
    .p2align 4, 0x90
PlaySoundW:
    jmp *ptr_PlaySoundW(%rip)

    .globl SendDriverMessage
    .p2align 4, 0x90
SendDriverMessage:
    jmp *ptr_SendDriverMessage(%rip)

    .globl sndPlaySoundA
    .p2align 4, 0x90
sndPlaySoundA:
    jmp *ptr_sndPlaySoundA(%rip)

    .globl sndPlaySoundW
    .p2align 4, 0x90
sndPlaySoundW:
    jmp *ptr_sndPlaySoundW(%rip)

    .globl timeBeginPeriod
    .p2align 4, 0x90
timeBeginPeriod:
    jmp *ptr_timeBeginPeriod(%rip)

    .globl timeEndPeriod
    .p2align 4, 0x90
timeEndPeriod:
    jmp *ptr_timeEndPeriod(%rip)

    .globl timeGetDevCaps
    .p2align 4, 0x90
timeGetDevCaps:
    jmp *ptr_timeGetDevCaps(%rip)

    .globl timeGetSystemTime
    .p2align 4, 0x90
timeGetSystemTime:
    jmp *ptr_timeGetSystemTime(%rip)

    .globl timeGetTime
    .p2align 4, 0x90
timeGetTime:
    jmp *ptr_timeGetTime(%rip)

    .globl timeKillEvent
    .p2align 4, 0x90
timeKillEvent:
    jmp *ptr_timeKillEvent(%rip)

    .globl timeSetEvent
    .p2align 4, 0x90
timeSetEvent:
    jmp *ptr_timeSetEvent(%rip)

    .globl waveInAddBuffer
    .p2align 4, 0x90
waveInAddBuffer:
    jmp *ptr_waveInAddBuffer(%rip)

    .globl waveInClose
    .p2align 4, 0x90
waveInClose:
    jmp *ptr_waveInClose(%rip)

    .globl waveInGetDevCapsA
    .p2align 4, 0x90
waveInGetDevCapsA:
    jmp *ptr_waveInGetDevCapsA(%rip)

    .globl waveInGetDevCapsW
    .p2align 4, 0x90
waveInGetDevCapsW:
    jmp *ptr_waveInGetDevCapsW(%rip)

    .globl waveInGetErrorTextA
    .p2align 4, 0x90
waveInGetErrorTextA:
    jmp *ptr_waveInGetErrorTextA(%rip)

    .globl waveInGetErrorTextW
    .p2align 4, 0x90
waveInGetErrorTextW:
    jmp *ptr_waveInGetErrorTextW(%rip)

    .globl waveInGetID
    .p2align 4, 0x90
waveInGetID:
    jmp *ptr_waveInGetID(%rip)

    .globl waveInGetNumDevs
    .p2align 4, 0x90
waveInGetNumDevs:
    jmp *ptr_waveInGetNumDevs(%rip)

    .globl waveInGetPosition
    .p2align 4, 0x90
waveInGetPosition:
    jmp *ptr_waveInGetPosition(%rip)

    .globl waveInMessage
    .p2align 4, 0x90
waveInMessage:
    jmp *ptr_waveInMessage(%rip)

    .globl waveInOpen
    .p2align 4, 0x90
waveInOpen:
    jmp *ptr_waveInOpen(%rip)

    .globl waveInPrepareHeader
    .p2align 4, 0x90
waveInPrepareHeader:
    jmp *ptr_waveInPrepareHeader(%rip)

    .globl waveInReset
    .p2align 4, 0x90
waveInReset:
    jmp *ptr_waveInReset(%rip)

    .globl waveInStart
    .p2align 4, 0x90
waveInStart:
    jmp *ptr_waveInStart(%rip)

    .globl waveInStop
    .p2align 4, 0x90
waveInStop:
    jmp *ptr_waveInStop(%rip)

    .globl waveInUnprepareHeader
    .p2align 4, 0x90
waveInUnprepareHeader:
    jmp *ptr_waveInUnprepareHeader(%rip)

    .globl waveOutBreakLoop
    .p2align 4, 0x90
waveOutBreakLoop:
    jmp *ptr_waveOutBreakLoop(%rip)

    .globl waveOutClose
    .p2align 4, 0x90
waveOutClose:
    jmp *ptr_waveOutClose(%rip)

    .globl waveOutGetDevCapsA
    .p2align 4, 0x90
waveOutGetDevCapsA:
    jmp *ptr_waveOutGetDevCapsA(%rip)

    .globl waveOutGetDevCapsW
    .p2align 4, 0x90
waveOutGetDevCapsW:
    jmp *ptr_waveOutGetDevCapsW(%rip)

    .globl waveOutGetErrorTextA
    .p2align 4, 0x90
waveOutGetErrorTextA:
    jmp *ptr_waveOutGetErrorTextA(%rip)

    .globl waveOutGetErrorTextW
    .p2align 4, 0x90
waveOutGetErrorTextW:
    jmp *ptr_waveOutGetErrorTextW(%rip)

    .globl waveOutGetID
    .p2align 4, 0x90
waveOutGetID:
    jmp *ptr_waveOutGetID(%rip)

    .globl waveOutGetNumDevs
    .p2align 4, 0x90
waveOutGetNumDevs:
    jmp *ptr_waveOutGetNumDevs(%rip)

    .globl waveOutGetPitch
    .p2align 4, 0x90
waveOutGetPitch:
    jmp *ptr_waveOutGetPitch(%rip)

    .globl waveOutGetPlaybackRate
    .p2align 4, 0x90
waveOutGetPlaybackRate:
    jmp *ptr_waveOutGetPlaybackRate(%rip)

    .globl waveOutGetPosition
    .p2align 4, 0x90
waveOutGetPosition:
    jmp *ptr_waveOutGetPosition(%rip)

    .globl waveOutGetVolume
    .p2align 4, 0x90
waveOutGetVolume:
    jmp *ptr_waveOutGetVolume(%rip)

    .globl waveOutMessage
    .p2align 4, 0x90
waveOutMessage:
    jmp *ptr_waveOutMessage(%rip)

    .globl waveOutOpen
    .p2align 4, 0x90
waveOutOpen:
    jmp *ptr_waveOutOpen(%rip)

    .globl waveOutPause
    .p2align 4, 0x90
waveOutPause:
    jmp *ptr_waveOutPause(%rip)

    .globl waveOutPrepareHeader
    .p2align 4, 0x90
waveOutPrepareHeader:
    jmp *ptr_waveOutPrepareHeader(%rip)

    .globl waveOutReset
    .p2align 4, 0x90
waveOutReset:
    jmp *ptr_waveOutReset(%rip)

    .globl waveOutRestart
    .p2align 4, 0x90
waveOutRestart:
    jmp *ptr_waveOutRestart(%rip)

    .globl waveOutSetPitch
    .p2align 4, 0x90
waveOutSetPitch:
    jmp *ptr_waveOutSetPitch(%rip)

    .globl waveOutSetPlaybackRate
    .p2align 4, 0x90
waveOutSetPlaybackRate:
    jmp *ptr_waveOutSetPlaybackRate(%rip)

    .globl waveOutSetVolume
    .p2align 4, 0x90
waveOutSetVolume:
    jmp *ptr_waveOutSetVolume(%rip)

    .globl waveOutUnprepareHeader
    .p2align 4, 0x90
waveOutUnprepareHeader:
    jmp *ptr_waveOutUnprepareHeader(%rip)

    .globl waveOutWrite
    .p2align 4, 0x90
waveOutWrite:
    jmp *ptr_waveOutWrite(%rip)

    .globl WOWAppExit
    .p2align 4, 0x90
WOWAppExit:
    jmp *ptr_WOWAppExit(%rip)

