/* GENERATED by tools/gen_winmm_forwarders.ps1 - do not edit by hand. */
#include <windows.h>
#include "winmm_forward.h"
#include "log.h"

/* Each ptr_NAME slot is what the matching assembly thunk in winmm_forward.s
 * jmp *ptr_NAME(%rip)s through. Defaulted to a safe logging stub so a
 * call before winmm_forward_init() (or to a name the real DLL somehow
 * lacks) logs instead of crashing. */

static DWORD_PTR stub_auxGetDevCapsA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "auxGetDevCapsA");
    return 0;
}
void *ptr_auxGetDevCapsA = (void*)stub_auxGetDevCapsA;

static DWORD_PTR stub_auxGetDevCapsW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "auxGetDevCapsW");
    return 0;
}
void *ptr_auxGetDevCapsW = (void*)stub_auxGetDevCapsW;

static DWORD_PTR stub_auxGetNumDevs(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "auxGetNumDevs");
    return 0;
}
void *ptr_auxGetNumDevs = (void*)stub_auxGetNumDevs;

static DWORD_PTR stub_auxGetVolume(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "auxGetVolume");
    return 0;
}
void *ptr_auxGetVolume = (void*)stub_auxGetVolume;

static DWORD_PTR stub_auxOutMessage(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "auxOutMessage");
    return 0;
}
void *ptr_auxOutMessage = (void*)stub_auxOutMessage;

static DWORD_PTR stub_auxSetVolume(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "auxSetVolume");
    return 0;
}
void *ptr_auxSetVolume = (void*)stub_auxSetVolume;

static DWORD_PTR stub_CloseDriver(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "CloseDriver");
    return 0;
}
void *ptr_CloseDriver = (void*)stub_CloseDriver;

static DWORD_PTR stub_DefDriverProc(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "DefDriverProc");
    return 0;
}
void *ptr_DefDriverProc = (void*)stub_DefDriverProc;

static DWORD_PTR stub_DriverCallback(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "DriverCallback");
    return 0;
}
void *ptr_DriverCallback = (void*)stub_DriverCallback;

static DWORD_PTR stub_DrvGetModuleHandle(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "DrvGetModuleHandle");
    return 0;
}
void *ptr_DrvGetModuleHandle = (void*)stub_DrvGetModuleHandle;

static DWORD_PTR stub_GetDriverModuleHandle(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "GetDriverModuleHandle");
    return 0;
}
void *ptr_GetDriverModuleHandle = (void*)stub_GetDriverModuleHandle;

static DWORD_PTR stub_joyConfigChanged(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joyConfigChanged");
    return 0;
}
void *ptr_joyConfigChanged = (void*)stub_joyConfigChanged;

static DWORD_PTR stub_joyGetDevCapsA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joyGetDevCapsA");
    return 0;
}
void *ptr_joyGetDevCapsA = (void*)stub_joyGetDevCapsA;

static DWORD_PTR stub_joyGetDevCapsW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joyGetDevCapsW");
    return 0;
}
void *ptr_joyGetDevCapsW = (void*)stub_joyGetDevCapsW;

static DWORD_PTR stub_joyGetNumDevs(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joyGetNumDevs");
    return 0;
}
void *ptr_joyGetNumDevs = (void*)stub_joyGetNumDevs;

static DWORD_PTR stub_joyGetPos(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joyGetPos");
    return 0;
}
void *ptr_joyGetPos = (void*)stub_joyGetPos;

static DWORD_PTR stub_joyGetPosEx(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joyGetPosEx");
    return 0;
}
void *ptr_joyGetPosEx = (void*)stub_joyGetPosEx;

static DWORD_PTR stub_joyGetThreshold(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joyGetThreshold");
    return 0;
}
void *ptr_joyGetThreshold = (void*)stub_joyGetThreshold;

static DWORD_PTR stub_joyReleaseCapture(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joyReleaseCapture");
    return 0;
}
void *ptr_joyReleaseCapture = (void*)stub_joyReleaseCapture;

static DWORD_PTR stub_joySetCapture(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joySetCapture");
    return 0;
}
void *ptr_joySetCapture = (void*)stub_joySetCapture;

static DWORD_PTR stub_joySetThreshold(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "joySetThreshold");
    return 0;
}
void *ptr_joySetThreshold = (void*)stub_joySetThreshold;

static DWORD_PTR stub_mciDriverNotify(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciDriverNotify");
    return 0;
}
void *ptr_mciDriverNotify = (void*)stub_mciDriverNotify;

static DWORD_PTR stub_mciDriverYield(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciDriverYield");
    return 0;
}
void *ptr_mciDriverYield = (void*)stub_mciDriverYield;

static DWORD_PTR stub_mciExecute(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciExecute");
    return 0;
}
void *ptr_mciExecute = (void*)stub_mciExecute;

static DWORD_PTR stub_mciFreeCommandResource(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciFreeCommandResource");
    return 0;
}
void *ptr_mciFreeCommandResource = (void*)stub_mciFreeCommandResource;

static DWORD_PTR stub_mciGetCreatorTask(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciGetCreatorTask");
    return 0;
}
void *ptr_mciGetCreatorTask = (void*)stub_mciGetCreatorTask;

static DWORD_PTR stub_mciGetDeviceIDA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciGetDeviceIDA");
    return 0;
}
void *ptr_mciGetDeviceIDA = (void*)stub_mciGetDeviceIDA;

static DWORD_PTR stub_mciGetDeviceIDFromElementIDA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciGetDeviceIDFromElementIDA");
    return 0;
}
void *ptr_mciGetDeviceIDFromElementIDA = (void*)stub_mciGetDeviceIDFromElementIDA;

static DWORD_PTR stub_mciGetDeviceIDFromElementIDW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciGetDeviceIDFromElementIDW");
    return 0;
}
void *ptr_mciGetDeviceIDFromElementIDW = (void*)stub_mciGetDeviceIDFromElementIDW;

static DWORD_PTR stub_mciGetDeviceIDW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciGetDeviceIDW");
    return 0;
}
void *ptr_mciGetDeviceIDW = (void*)stub_mciGetDeviceIDW;

static DWORD_PTR stub_mciGetDriverData(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciGetDriverData");
    return 0;
}
void *ptr_mciGetDriverData = (void*)stub_mciGetDriverData;

static DWORD_PTR stub_mciGetErrorStringA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciGetErrorStringA");
    return 0;
}
void *ptr_mciGetErrorStringA = (void*)stub_mciGetErrorStringA;

static DWORD_PTR stub_mciGetErrorStringW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciGetErrorStringW");
    return 0;
}
void *ptr_mciGetErrorStringW = (void*)stub_mciGetErrorStringW;

static DWORD_PTR stub_mciGetYieldProc(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciGetYieldProc");
    return 0;
}
void *ptr_mciGetYieldProc = (void*)stub_mciGetYieldProc;

static DWORD_PTR stub_mciLoadCommandResource(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciLoadCommandResource");
    return 0;
}
void *ptr_mciLoadCommandResource = (void*)stub_mciLoadCommandResource;

static DWORD_PTR stub_mciSendCommandA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciSendCommandA");
    return 0;
}
void *ptr_mciSendCommandA = (void*)stub_mciSendCommandA;

static DWORD_PTR stub_mciSendCommandW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciSendCommandW");
    return 0;
}
void *ptr_mciSendCommandW = (void*)stub_mciSendCommandW;

static DWORD_PTR stub_mciSendStringA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciSendStringA");
    return 0;
}
void *ptr_mciSendStringA = (void*)stub_mciSendStringA;

static DWORD_PTR stub_mciSendStringW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciSendStringW");
    return 0;
}
void *ptr_mciSendStringW = (void*)stub_mciSendStringW;

static DWORD_PTR stub_mciSetDriverData(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciSetDriverData");
    return 0;
}
void *ptr_mciSetDriverData = (void*)stub_mciSetDriverData;

static DWORD_PTR stub_mciSetYieldProc(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mciSetYieldProc");
    return 0;
}
void *ptr_mciSetYieldProc = (void*)stub_mciSetYieldProc;

static DWORD_PTR stub_midiConnect(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiConnect");
    return 0;
}
void *ptr_midiConnect = (void*)stub_midiConnect;

static DWORD_PTR stub_midiDisconnect(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiDisconnect");
    return 0;
}
void *ptr_midiDisconnect = (void*)stub_midiDisconnect;

static DWORD_PTR stub_midiInAddBuffer(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInAddBuffer");
    return 0;
}
void *ptr_midiInAddBuffer = (void*)stub_midiInAddBuffer;

static DWORD_PTR stub_midiInClose(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInClose");
    return 0;
}
void *ptr_midiInClose = (void*)stub_midiInClose;

static DWORD_PTR stub_midiInGetDevCapsA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInGetDevCapsA");
    return 0;
}
void *ptr_midiInGetDevCapsA = (void*)stub_midiInGetDevCapsA;

static DWORD_PTR stub_midiInGetDevCapsW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInGetDevCapsW");
    return 0;
}
void *ptr_midiInGetDevCapsW = (void*)stub_midiInGetDevCapsW;

static DWORD_PTR stub_midiInGetErrorTextA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInGetErrorTextA");
    return 0;
}
void *ptr_midiInGetErrorTextA = (void*)stub_midiInGetErrorTextA;

static DWORD_PTR stub_midiInGetErrorTextW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInGetErrorTextW");
    return 0;
}
void *ptr_midiInGetErrorTextW = (void*)stub_midiInGetErrorTextW;

static DWORD_PTR stub_midiInGetID(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInGetID");
    return 0;
}
void *ptr_midiInGetID = (void*)stub_midiInGetID;

static DWORD_PTR stub_midiInGetNumDevs(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInGetNumDevs");
    return 0;
}
void *ptr_midiInGetNumDevs = (void*)stub_midiInGetNumDevs;

static DWORD_PTR stub_midiInMessage(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInMessage");
    return 0;
}
void *ptr_midiInMessage = (void*)stub_midiInMessage;

static DWORD_PTR stub_midiInOpen(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInOpen");
    return 0;
}
void *ptr_midiInOpen = (void*)stub_midiInOpen;

static DWORD_PTR stub_midiInPrepareHeader(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInPrepareHeader");
    return 0;
}
void *ptr_midiInPrepareHeader = (void*)stub_midiInPrepareHeader;

static DWORD_PTR stub_midiInReset(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInReset");
    return 0;
}
void *ptr_midiInReset = (void*)stub_midiInReset;

static DWORD_PTR stub_midiInStart(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInStart");
    return 0;
}
void *ptr_midiInStart = (void*)stub_midiInStart;

static DWORD_PTR stub_midiInStop(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInStop");
    return 0;
}
void *ptr_midiInStop = (void*)stub_midiInStop;

static DWORD_PTR stub_midiInUnprepareHeader(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiInUnprepareHeader");
    return 0;
}
void *ptr_midiInUnprepareHeader = (void*)stub_midiInUnprepareHeader;

static DWORD_PTR stub_midiOutCacheDrumPatches(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutCacheDrumPatches");
    return 0;
}
void *ptr_midiOutCacheDrumPatches = (void*)stub_midiOutCacheDrumPatches;

static DWORD_PTR stub_midiOutCachePatches(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutCachePatches");
    return 0;
}
void *ptr_midiOutCachePatches = (void*)stub_midiOutCachePatches;

static DWORD_PTR stub_midiOutClose(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutClose");
    return 0;
}
void *ptr_midiOutClose = (void*)stub_midiOutClose;

static DWORD_PTR stub_midiOutGetDevCapsA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutGetDevCapsA");
    return 0;
}
void *ptr_midiOutGetDevCapsA = (void*)stub_midiOutGetDevCapsA;

static DWORD_PTR stub_midiOutGetDevCapsW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutGetDevCapsW");
    return 0;
}
void *ptr_midiOutGetDevCapsW = (void*)stub_midiOutGetDevCapsW;

static DWORD_PTR stub_midiOutGetErrorTextA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutGetErrorTextA");
    return 0;
}
void *ptr_midiOutGetErrorTextA = (void*)stub_midiOutGetErrorTextA;

static DWORD_PTR stub_midiOutGetErrorTextW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutGetErrorTextW");
    return 0;
}
void *ptr_midiOutGetErrorTextW = (void*)stub_midiOutGetErrorTextW;

static DWORD_PTR stub_midiOutGetID(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutGetID");
    return 0;
}
void *ptr_midiOutGetID = (void*)stub_midiOutGetID;

static DWORD_PTR stub_midiOutGetNumDevs(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutGetNumDevs");
    return 0;
}
void *ptr_midiOutGetNumDevs = (void*)stub_midiOutGetNumDevs;

static DWORD_PTR stub_midiOutGetVolume(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutGetVolume");
    return 0;
}
void *ptr_midiOutGetVolume = (void*)stub_midiOutGetVolume;

static DWORD_PTR stub_midiOutLongMsg(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutLongMsg");
    return 0;
}
void *ptr_midiOutLongMsg = (void*)stub_midiOutLongMsg;

static DWORD_PTR stub_midiOutMessage(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutMessage");
    return 0;
}
void *ptr_midiOutMessage = (void*)stub_midiOutMessage;

static DWORD_PTR stub_midiOutOpen(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutOpen");
    return 0;
}
void *ptr_midiOutOpen = (void*)stub_midiOutOpen;

static DWORD_PTR stub_midiOutPrepareHeader(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutPrepareHeader");
    return 0;
}
void *ptr_midiOutPrepareHeader = (void*)stub_midiOutPrepareHeader;

static DWORD_PTR stub_midiOutReset(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutReset");
    return 0;
}
void *ptr_midiOutReset = (void*)stub_midiOutReset;

static DWORD_PTR stub_midiOutSetVolume(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutSetVolume");
    return 0;
}
void *ptr_midiOutSetVolume = (void*)stub_midiOutSetVolume;

static DWORD_PTR stub_midiOutShortMsg(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutShortMsg");
    return 0;
}
void *ptr_midiOutShortMsg = (void*)stub_midiOutShortMsg;

static DWORD_PTR stub_midiOutUnprepareHeader(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiOutUnprepareHeader");
    return 0;
}
void *ptr_midiOutUnprepareHeader = (void*)stub_midiOutUnprepareHeader;

static DWORD_PTR stub_midiStreamClose(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiStreamClose");
    return 0;
}
void *ptr_midiStreamClose = (void*)stub_midiStreamClose;

static DWORD_PTR stub_midiStreamOpen(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiStreamOpen");
    return 0;
}
void *ptr_midiStreamOpen = (void*)stub_midiStreamOpen;

static DWORD_PTR stub_midiStreamOut(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiStreamOut");
    return 0;
}
void *ptr_midiStreamOut = (void*)stub_midiStreamOut;

static DWORD_PTR stub_midiStreamPause(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiStreamPause");
    return 0;
}
void *ptr_midiStreamPause = (void*)stub_midiStreamPause;

static DWORD_PTR stub_midiStreamPosition(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiStreamPosition");
    return 0;
}
void *ptr_midiStreamPosition = (void*)stub_midiStreamPosition;

static DWORD_PTR stub_midiStreamProperty(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiStreamProperty");
    return 0;
}
void *ptr_midiStreamProperty = (void*)stub_midiStreamProperty;

static DWORD_PTR stub_midiStreamRestart(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiStreamRestart");
    return 0;
}
void *ptr_midiStreamRestart = (void*)stub_midiStreamRestart;

static DWORD_PTR stub_midiStreamStop(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "midiStreamStop");
    return 0;
}
void *ptr_midiStreamStop = (void*)stub_midiStreamStop;

static DWORD_PTR stub_mixerClose(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerClose");
    return 0;
}
void *ptr_mixerClose = (void*)stub_mixerClose;

static DWORD_PTR stub_mixerGetControlDetailsA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetControlDetailsA");
    return 0;
}
void *ptr_mixerGetControlDetailsA = (void*)stub_mixerGetControlDetailsA;

static DWORD_PTR stub_mixerGetControlDetailsW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetControlDetailsW");
    return 0;
}
void *ptr_mixerGetControlDetailsW = (void*)stub_mixerGetControlDetailsW;

static DWORD_PTR stub_mixerGetDevCapsA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetDevCapsA");
    return 0;
}
void *ptr_mixerGetDevCapsA = (void*)stub_mixerGetDevCapsA;

static DWORD_PTR stub_mixerGetDevCapsW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetDevCapsW");
    return 0;
}
void *ptr_mixerGetDevCapsW = (void*)stub_mixerGetDevCapsW;

static DWORD_PTR stub_mixerGetID(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetID");
    return 0;
}
void *ptr_mixerGetID = (void*)stub_mixerGetID;

static DWORD_PTR stub_mixerGetLineControlsA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetLineControlsA");
    return 0;
}
void *ptr_mixerGetLineControlsA = (void*)stub_mixerGetLineControlsA;

static DWORD_PTR stub_mixerGetLineControlsW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetLineControlsW");
    return 0;
}
void *ptr_mixerGetLineControlsW = (void*)stub_mixerGetLineControlsW;

static DWORD_PTR stub_mixerGetLineInfoA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetLineInfoA");
    return 0;
}
void *ptr_mixerGetLineInfoA = (void*)stub_mixerGetLineInfoA;

static DWORD_PTR stub_mixerGetLineInfoW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetLineInfoW");
    return 0;
}
void *ptr_mixerGetLineInfoW = (void*)stub_mixerGetLineInfoW;

static DWORD_PTR stub_mixerGetNumDevs(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerGetNumDevs");
    return 0;
}
void *ptr_mixerGetNumDevs = (void*)stub_mixerGetNumDevs;

static DWORD_PTR stub_mixerMessage(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerMessage");
    return 0;
}
void *ptr_mixerMessage = (void*)stub_mixerMessage;

static DWORD_PTR stub_mixerOpen(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerOpen");
    return 0;
}
void *ptr_mixerOpen = (void*)stub_mixerOpen;

static DWORD_PTR stub_mixerSetControlDetails(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mixerSetControlDetails");
    return 0;
}
void *ptr_mixerSetControlDetails = (void*)stub_mixerSetControlDetails;

static DWORD_PTR stub_mmDrvInstall(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmDrvInstall");
    return 0;
}
void *ptr_mmDrvInstall = (void*)stub_mmDrvInstall;

static DWORD_PTR stub_mmGetCurrentTask(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmGetCurrentTask");
    return 0;
}
void *ptr_mmGetCurrentTask = (void*)stub_mmGetCurrentTask;

static DWORD_PTR stub_mmioAdvance(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioAdvance");
    return 0;
}
void *ptr_mmioAdvance = (void*)stub_mmioAdvance;

static DWORD_PTR stub_mmioAscend(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioAscend");
    return 0;
}
void *ptr_mmioAscend = (void*)stub_mmioAscend;

static DWORD_PTR stub_mmioClose(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioClose");
    return 0;
}
void *ptr_mmioClose = (void*)stub_mmioClose;

static DWORD_PTR stub_mmioCreateChunk(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioCreateChunk");
    return 0;
}
void *ptr_mmioCreateChunk = (void*)stub_mmioCreateChunk;

static DWORD_PTR stub_mmioDescend(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioDescend");
    return 0;
}
void *ptr_mmioDescend = (void*)stub_mmioDescend;

static DWORD_PTR stub_mmioFlush(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioFlush");
    return 0;
}
void *ptr_mmioFlush = (void*)stub_mmioFlush;

static DWORD_PTR stub_mmioGetInfo(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioGetInfo");
    return 0;
}
void *ptr_mmioGetInfo = (void*)stub_mmioGetInfo;

static DWORD_PTR stub_mmioInstallIOProcA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioInstallIOProcA");
    return 0;
}
void *ptr_mmioInstallIOProcA = (void*)stub_mmioInstallIOProcA;

static DWORD_PTR stub_mmioInstallIOProcW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioInstallIOProcW");
    return 0;
}
void *ptr_mmioInstallIOProcW = (void*)stub_mmioInstallIOProcW;

static DWORD_PTR stub_mmioOpenA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioOpenA");
    return 0;
}
void *ptr_mmioOpenA = (void*)stub_mmioOpenA;

static DWORD_PTR stub_mmioOpenW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioOpenW");
    return 0;
}
void *ptr_mmioOpenW = (void*)stub_mmioOpenW;

static DWORD_PTR stub_mmioRead(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioRead");
    return 0;
}
void *ptr_mmioRead = (void*)stub_mmioRead;

static DWORD_PTR stub_mmioRenameA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioRenameA");
    return 0;
}
void *ptr_mmioRenameA = (void*)stub_mmioRenameA;

static DWORD_PTR stub_mmioRenameW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioRenameW");
    return 0;
}
void *ptr_mmioRenameW = (void*)stub_mmioRenameW;

static DWORD_PTR stub_mmioSeek(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioSeek");
    return 0;
}
void *ptr_mmioSeek = (void*)stub_mmioSeek;

static DWORD_PTR stub_mmioSendMessage(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioSendMessage");
    return 0;
}
void *ptr_mmioSendMessage = (void*)stub_mmioSendMessage;

static DWORD_PTR stub_mmioSetBuffer(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioSetBuffer");
    return 0;
}
void *ptr_mmioSetBuffer = (void*)stub_mmioSetBuffer;

static DWORD_PTR stub_mmioSetInfo(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioSetInfo");
    return 0;
}
void *ptr_mmioSetInfo = (void*)stub_mmioSetInfo;

static DWORD_PTR stub_mmioStringToFOURCCA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioStringToFOURCCA");
    return 0;
}
void *ptr_mmioStringToFOURCCA = (void*)stub_mmioStringToFOURCCA;

static DWORD_PTR stub_mmioStringToFOURCCW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioStringToFOURCCW");
    return 0;
}
void *ptr_mmioStringToFOURCCW = (void*)stub_mmioStringToFOURCCW;

static DWORD_PTR stub_mmioWrite(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmioWrite");
    return 0;
}
void *ptr_mmioWrite = (void*)stub_mmioWrite;

static DWORD_PTR stub_mmsystemGetVersion(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmsystemGetVersion");
    return 0;
}
void *ptr_mmsystemGetVersion = (void*)stub_mmsystemGetVersion;

static DWORD_PTR stub_mmTaskBlock(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmTaskBlock");
    return 0;
}
void *ptr_mmTaskBlock = (void*)stub_mmTaskBlock;

static DWORD_PTR stub_mmTaskCreate(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmTaskCreate");
    return 0;
}
void *ptr_mmTaskCreate = (void*)stub_mmTaskCreate;

static DWORD_PTR stub_mmTaskSignal(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmTaskSignal");
    return 0;
}
void *ptr_mmTaskSignal = (void*)stub_mmTaskSignal;

static DWORD_PTR stub_mmTaskYield(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "mmTaskYield");
    return 0;
}
void *ptr_mmTaskYield = (void*)stub_mmTaskYield;

static DWORD_PTR stub_OpenDriver(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "OpenDriver");
    return 0;
}
void *ptr_OpenDriver = (void*)stub_OpenDriver;

static DWORD_PTR stub_PlaySound(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "PlaySound");
    return 0;
}
void *ptr_PlaySound = (void*)stub_PlaySound;

static DWORD_PTR stub_PlaySoundA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "PlaySoundA");
    return 0;
}
void *ptr_PlaySoundA = (void*)stub_PlaySoundA;

static DWORD_PTR stub_PlaySoundW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "PlaySoundW");
    return 0;
}
void *ptr_PlaySoundW = (void*)stub_PlaySoundW;

static DWORD_PTR stub_SendDriverMessage(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "SendDriverMessage");
    return 0;
}
void *ptr_SendDriverMessage = (void*)stub_SendDriverMessage;

static DWORD_PTR stub_sndPlaySoundA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "sndPlaySoundA");
    return 0;
}
void *ptr_sndPlaySoundA = (void*)stub_sndPlaySoundA;

static DWORD_PTR stub_sndPlaySoundW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "sndPlaySoundW");
    return 0;
}
void *ptr_sndPlaySoundW = (void*)stub_sndPlaySoundW;

static DWORD_PTR stub_timeBeginPeriod(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "timeBeginPeriod");
    return 0;
}
void *ptr_timeBeginPeriod = (void*)stub_timeBeginPeriod;

static DWORD_PTR stub_timeEndPeriod(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "timeEndPeriod");
    return 0;
}
void *ptr_timeEndPeriod = (void*)stub_timeEndPeriod;

static DWORD_PTR stub_timeGetDevCaps(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "timeGetDevCaps");
    return 0;
}
void *ptr_timeGetDevCaps = (void*)stub_timeGetDevCaps;

static DWORD_PTR stub_timeGetSystemTime(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "timeGetSystemTime");
    return 0;
}
void *ptr_timeGetSystemTime = (void*)stub_timeGetSystemTime;

static DWORD_PTR stub_timeGetTime(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "timeGetTime");
    return 0;
}
void *ptr_timeGetTime = (void*)stub_timeGetTime;

static DWORD_PTR stub_timeKillEvent(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "timeKillEvent");
    return 0;
}
void *ptr_timeKillEvent = (void*)stub_timeKillEvent;

static DWORD_PTR stub_timeSetEvent(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "timeSetEvent");
    return 0;
}
void *ptr_timeSetEvent = (void*)stub_timeSetEvent;

static DWORD_PTR stub_waveInAddBuffer(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInAddBuffer");
    return 0;
}
void *ptr_waveInAddBuffer = (void*)stub_waveInAddBuffer;

static DWORD_PTR stub_waveInClose(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInClose");
    return 0;
}
void *ptr_waveInClose = (void*)stub_waveInClose;

static DWORD_PTR stub_waveInGetDevCapsA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInGetDevCapsA");
    return 0;
}
void *ptr_waveInGetDevCapsA = (void*)stub_waveInGetDevCapsA;

static DWORD_PTR stub_waveInGetDevCapsW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInGetDevCapsW");
    return 0;
}
void *ptr_waveInGetDevCapsW = (void*)stub_waveInGetDevCapsW;

static DWORD_PTR stub_waveInGetErrorTextA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInGetErrorTextA");
    return 0;
}
void *ptr_waveInGetErrorTextA = (void*)stub_waveInGetErrorTextA;

static DWORD_PTR stub_waveInGetErrorTextW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInGetErrorTextW");
    return 0;
}
void *ptr_waveInGetErrorTextW = (void*)stub_waveInGetErrorTextW;

static DWORD_PTR stub_waveInGetID(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInGetID");
    return 0;
}
void *ptr_waveInGetID = (void*)stub_waveInGetID;

static DWORD_PTR stub_waveInGetNumDevs(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInGetNumDevs");
    return 0;
}
void *ptr_waveInGetNumDevs = (void*)stub_waveInGetNumDevs;

static DWORD_PTR stub_waveInGetPosition(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInGetPosition");
    return 0;
}
void *ptr_waveInGetPosition = (void*)stub_waveInGetPosition;

static DWORD_PTR stub_waveInMessage(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInMessage");
    return 0;
}
void *ptr_waveInMessage = (void*)stub_waveInMessage;

static DWORD_PTR stub_waveInOpen(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInOpen");
    return 0;
}
void *ptr_waveInOpen = (void*)stub_waveInOpen;

static DWORD_PTR stub_waveInPrepareHeader(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInPrepareHeader");
    return 0;
}
void *ptr_waveInPrepareHeader = (void*)stub_waveInPrepareHeader;

static DWORD_PTR stub_waveInReset(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInReset");
    return 0;
}
void *ptr_waveInReset = (void*)stub_waveInReset;

static DWORD_PTR stub_waveInStart(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInStart");
    return 0;
}
void *ptr_waveInStart = (void*)stub_waveInStart;

static DWORD_PTR stub_waveInStop(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInStop");
    return 0;
}
void *ptr_waveInStop = (void*)stub_waveInStop;

static DWORD_PTR stub_waveInUnprepareHeader(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveInUnprepareHeader");
    return 0;
}
void *ptr_waveInUnprepareHeader = (void*)stub_waveInUnprepareHeader;

static DWORD_PTR stub_waveOutBreakLoop(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutBreakLoop");
    return 0;
}
void *ptr_waveOutBreakLoop = (void*)stub_waveOutBreakLoop;

static DWORD_PTR stub_waveOutClose(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutClose");
    return 0;
}
void *ptr_waveOutClose = (void*)stub_waveOutClose;

static DWORD_PTR stub_waveOutGetDevCapsA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetDevCapsA");
    return 0;
}
void *ptr_waveOutGetDevCapsA = (void*)stub_waveOutGetDevCapsA;

static DWORD_PTR stub_waveOutGetDevCapsW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetDevCapsW");
    return 0;
}
void *ptr_waveOutGetDevCapsW = (void*)stub_waveOutGetDevCapsW;

static DWORD_PTR stub_waveOutGetErrorTextA(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetErrorTextA");
    return 0;
}
void *ptr_waveOutGetErrorTextA = (void*)stub_waveOutGetErrorTextA;

static DWORD_PTR stub_waveOutGetErrorTextW(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetErrorTextW");
    return 0;
}
void *ptr_waveOutGetErrorTextW = (void*)stub_waveOutGetErrorTextW;

static DWORD_PTR stub_waveOutGetID(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetID");
    return 0;
}
void *ptr_waveOutGetID = (void*)stub_waveOutGetID;

static DWORD_PTR stub_waveOutGetNumDevs(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetNumDevs");
    return 0;
}
void *ptr_waveOutGetNumDevs = (void*)stub_waveOutGetNumDevs;

static DWORD_PTR stub_waveOutGetPitch(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetPitch");
    return 0;
}
void *ptr_waveOutGetPitch = (void*)stub_waveOutGetPitch;

static DWORD_PTR stub_waveOutGetPlaybackRate(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetPlaybackRate");
    return 0;
}
void *ptr_waveOutGetPlaybackRate = (void*)stub_waveOutGetPlaybackRate;

static DWORD_PTR stub_waveOutGetPosition(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetPosition");
    return 0;
}
void *ptr_waveOutGetPosition = (void*)stub_waveOutGetPosition;

static DWORD_PTR stub_waveOutGetVolume(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutGetVolume");
    return 0;
}
void *ptr_waveOutGetVolume = (void*)stub_waveOutGetVolume;

static DWORD_PTR stub_waveOutMessage(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutMessage");
    return 0;
}
void *ptr_waveOutMessage = (void*)stub_waveOutMessage;

static DWORD_PTR stub_waveOutOpen(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutOpen");
    return 0;
}
void *ptr_waveOutOpen = (void*)stub_waveOutOpen;

static DWORD_PTR stub_waveOutPause(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutPause");
    return 0;
}
void *ptr_waveOutPause = (void*)stub_waveOutPause;

static DWORD_PTR stub_waveOutPrepareHeader(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutPrepareHeader");
    return 0;
}
void *ptr_waveOutPrepareHeader = (void*)stub_waveOutPrepareHeader;

static DWORD_PTR stub_waveOutReset(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutReset");
    return 0;
}
void *ptr_waveOutReset = (void*)stub_waveOutReset;

static DWORD_PTR stub_waveOutRestart(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutRestart");
    return 0;
}
void *ptr_waveOutRestart = (void*)stub_waveOutRestart;

static DWORD_PTR stub_waveOutSetPitch(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutSetPitch");
    return 0;
}
void *ptr_waveOutSetPitch = (void*)stub_waveOutSetPitch;

static DWORD_PTR stub_waveOutSetPlaybackRate(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutSetPlaybackRate");
    return 0;
}
void *ptr_waveOutSetPlaybackRate = (void*)stub_waveOutSetPlaybackRate;

static DWORD_PTR stub_waveOutSetVolume(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutSetVolume");
    return 0;
}
void *ptr_waveOutSetVolume = (void*)stub_waveOutSetVolume;

static DWORD_PTR stub_waveOutUnprepareHeader(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutUnprepareHeader");
    return 0;
}
void *ptr_waveOutUnprepareHeader = (void*)stub_waveOutUnprepareHeader;

static DWORD_PTR stub_waveOutWrite(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "waveOutWrite");
    return 0;
}
void *ptr_waveOutWrite = (void*)stub_waveOutWrite;

static DWORD_PTR stub_WOWAppExit(void) {
    log_msg("winmm proxy: %s not resolved from real winmm.dll - returning 0", "WOWAppExit");
    return 0;
}
void *ptr_WOWAppExit = (void*)stub_WOWAppExit;

static HMODULE g_real_winmm = NULL;

void winmm_forward_init(void) {
    g_real_winmm = LoadLibraryW(L"C:\\Windows\\System32\\winmm.dll");
    if (!g_real_winmm) {
        log_msg("winmm proxy: FAILED to LoadLibraryW the real system winmm.dll (gle=%lu)", GetLastError());
        return; /* every export stays on its safe logging stub */
    }
    void *p;
    p = GetProcAddress(g_real_winmm, "auxGetDevCapsA"); if (p) ptr_auxGetDevCapsA = p;
    p = GetProcAddress(g_real_winmm, "auxGetDevCapsW"); if (p) ptr_auxGetDevCapsW = p;
    p = GetProcAddress(g_real_winmm, "auxGetNumDevs"); if (p) ptr_auxGetNumDevs = p;
    p = GetProcAddress(g_real_winmm, "auxGetVolume"); if (p) ptr_auxGetVolume = p;
    p = GetProcAddress(g_real_winmm, "auxOutMessage"); if (p) ptr_auxOutMessage = p;
    p = GetProcAddress(g_real_winmm, "auxSetVolume"); if (p) ptr_auxSetVolume = p;
    p = GetProcAddress(g_real_winmm, "CloseDriver"); if (p) ptr_CloseDriver = p;
    p = GetProcAddress(g_real_winmm, "DefDriverProc"); if (p) ptr_DefDriverProc = p;
    p = GetProcAddress(g_real_winmm, "DriverCallback"); if (p) ptr_DriverCallback = p;
    p = GetProcAddress(g_real_winmm, "DrvGetModuleHandle"); if (p) ptr_DrvGetModuleHandle = p;
    p = GetProcAddress(g_real_winmm, "GetDriverModuleHandle"); if (p) ptr_GetDriverModuleHandle = p;
    p = GetProcAddress(g_real_winmm, "joyConfigChanged"); if (p) ptr_joyConfigChanged = p;
    p = GetProcAddress(g_real_winmm, "joyGetDevCapsA"); if (p) ptr_joyGetDevCapsA = p;
    p = GetProcAddress(g_real_winmm, "joyGetDevCapsW"); if (p) ptr_joyGetDevCapsW = p;
    p = GetProcAddress(g_real_winmm, "joyGetNumDevs"); if (p) ptr_joyGetNumDevs = p;
    p = GetProcAddress(g_real_winmm, "joyGetPos"); if (p) ptr_joyGetPos = p;
    p = GetProcAddress(g_real_winmm, "joyGetPosEx"); if (p) ptr_joyGetPosEx = p;
    p = GetProcAddress(g_real_winmm, "joyGetThreshold"); if (p) ptr_joyGetThreshold = p;
    p = GetProcAddress(g_real_winmm, "joyReleaseCapture"); if (p) ptr_joyReleaseCapture = p;
    p = GetProcAddress(g_real_winmm, "joySetCapture"); if (p) ptr_joySetCapture = p;
    p = GetProcAddress(g_real_winmm, "joySetThreshold"); if (p) ptr_joySetThreshold = p;
    p = GetProcAddress(g_real_winmm, "mciDriverNotify"); if (p) ptr_mciDriverNotify = p;
    p = GetProcAddress(g_real_winmm, "mciDriverYield"); if (p) ptr_mciDriverYield = p;
    p = GetProcAddress(g_real_winmm, "mciExecute"); if (p) ptr_mciExecute = p;
    p = GetProcAddress(g_real_winmm, "mciFreeCommandResource"); if (p) ptr_mciFreeCommandResource = p;
    p = GetProcAddress(g_real_winmm, "mciGetCreatorTask"); if (p) ptr_mciGetCreatorTask = p;
    p = GetProcAddress(g_real_winmm, "mciGetDeviceIDA"); if (p) ptr_mciGetDeviceIDA = p;
    p = GetProcAddress(g_real_winmm, "mciGetDeviceIDFromElementIDA"); if (p) ptr_mciGetDeviceIDFromElementIDA = p;
    p = GetProcAddress(g_real_winmm, "mciGetDeviceIDFromElementIDW"); if (p) ptr_mciGetDeviceIDFromElementIDW = p;
    p = GetProcAddress(g_real_winmm, "mciGetDeviceIDW"); if (p) ptr_mciGetDeviceIDW = p;
    p = GetProcAddress(g_real_winmm, "mciGetDriverData"); if (p) ptr_mciGetDriverData = p;
    p = GetProcAddress(g_real_winmm, "mciGetErrorStringA"); if (p) ptr_mciGetErrorStringA = p;
    p = GetProcAddress(g_real_winmm, "mciGetErrorStringW"); if (p) ptr_mciGetErrorStringW = p;
    p = GetProcAddress(g_real_winmm, "mciGetYieldProc"); if (p) ptr_mciGetYieldProc = p;
    p = GetProcAddress(g_real_winmm, "mciLoadCommandResource"); if (p) ptr_mciLoadCommandResource = p;
    p = GetProcAddress(g_real_winmm, "mciSendCommandA"); if (p) ptr_mciSendCommandA = p;
    p = GetProcAddress(g_real_winmm, "mciSendCommandW"); if (p) ptr_mciSendCommandW = p;
    p = GetProcAddress(g_real_winmm, "mciSendStringA"); if (p) ptr_mciSendStringA = p;
    p = GetProcAddress(g_real_winmm, "mciSendStringW"); if (p) ptr_mciSendStringW = p;
    p = GetProcAddress(g_real_winmm, "mciSetDriverData"); if (p) ptr_mciSetDriverData = p;
    p = GetProcAddress(g_real_winmm, "mciSetYieldProc"); if (p) ptr_mciSetYieldProc = p;
    p = GetProcAddress(g_real_winmm, "midiConnect"); if (p) ptr_midiConnect = p;
    p = GetProcAddress(g_real_winmm, "midiDisconnect"); if (p) ptr_midiDisconnect = p;
    p = GetProcAddress(g_real_winmm, "midiInAddBuffer"); if (p) ptr_midiInAddBuffer = p;
    p = GetProcAddress(g_real_winmm, "midiInClose"); if (p) ptr_midiInClose = p;
    p = GetProcAddress(g_real_winmm, "midiInGetDevCapsA"); if (p) ptr_midiInGetDevCapsA = p;
    p = GetProcAddress(g_real_winmm, "midiInGetDevCapsW"); if (p) ptr_midiInGetDevCapsW = p;
    p = GetProcAddress(g_real_winmm, "midiInGetErrorTextA"); if (p) ptr_midiInGetErrorTextA = p;
    p = GetProcAddress(g_real_winmm, "midiInGetErrorTextW"); if (p) ptr_midiInGetErrorTextW = p;
    p = GetProcAddress(g_real_winmm, "midiInGetID"); if (p) ptr_midiInGetID = p;
    p = GetProcAddress(g_real_winmm, "midiInGetNumDevs"); if (p) ptr_midiInGetNumDevs = p;
    p = GetProcAddress(g_real_winmm, "midiInMessage"); if (p) ptr_midiInMessage = p;
    p = GetProcAddress(g_real_winmm, "midiInOpen"); if (p) ptr_midiInOpen = p;
    p = GetProcAddress(g_real_winmm, "midiInPrepareHeader"); if (p) ptr_midiInPrepareHeader = p;
    p = GetProcAddress(g_real_winmm, "midiInReset"); if (p) ptr_midiInReset = p;
    p = GetProcAddress(g_real_winmm, "midiInStart"); if (p) ptr_midiInStart = p;
    p = GetProcAddress(g_real_winmm, "midiInStop"); if (p) ptr_midiInStop = p;
    p = GetProcAddress(g_real_winmm, "midiInUnprepareHeader"); if (p) ptr_midiInUnprepareHeader = p;
    p = GetProcAddress(g_real_winmm, "midiOutCacheDrumPatches"); if (p) ptr_midiOutCacheDrumPatches = p;
    p = GetProcAddress(g_real_winmm, "midiOutCachePatches"); if (p) ptr_midiOutCachePatches = p;
    p = GetProcAddress(g_real_winmm, "midiOutClose"); if (p) ptr_midiOutClose = p;
    p = GetProcAddress(g_real_winmm, "midiOutGetDevCapsA"); if (p) ptr_midiOutGetDevCapsA = p;
    p = GetProcAddress(g_real_winmm, "midiOutGetDevCapsW"); if (p) ptr_midiOutGetDevCapsW = p;
    p = GetProcAddress(g_real_winmm, "midiOutGetErrorTextA"); if (p) ptr_midiOutGetErrorTextA = p;
    p = GetProcAddress(g_real_winmm, "midiOutGetErrorTextW"); if (p) ptr_midiOutGetErrorTextW = p;
    p = GetProcAddress(g_real_winmm, "midiOutGetID"); if (p) ptr_midiOutGetID = p;
    p = GetProcAddress(g_real_winmm, "midiOutGetNumDevs"); if (p) ptr_midiOutGetNumDevs = p;
    p = GetProcAddress(g_real_winmm, "midiOutGetVolume"); if (p) ptr_midiOutGetVolume = p;
    p = GetProcAddress(g_real_winmm, "midiOutLongMsg"); if (p) ptr_midiOutLongMsg = p;
    p = GetProcAddress(g_real_winmm, "midiOutMessage"); if (p) ptr_midiOutMessage = p;
    p = GetProcAddress(g_real_winmm, "midiOutOpen"); if (p) ptr_midiOutOpen = p;
    p = GetProcAddress(g_real_winmm, "midiOutPrepareHeader"); if (p) ptr_midiOutPrepareHeader = p;
    p = GetProcAddress(g_real_winmm, "midiOutReset"); if (p) ptr_midiOutReset = p;
    p = GetProcAddress(g_real_winmm, "midiOutSetVolume"); if (p) ptr_midiOutSetVolume = p;
    p = GetProcAddress(g_real_winmm, "midiOutShortMsg"); if (p) ptr_midiOutShortMsg = p;
    p = GetProcAddress(g_real_winmm, "midiOutUnprepareHeader"); if (p) ptr_midiOutUnprepareHeader = p;
    p = GetProcAddress(g_real_winmm, "midiStreamClose"); if (p) ptr_midiStreamClose = p;
    p = GetProcAddress(g_real_winmm, "midiStreamOpen"); if (p) ptr_midiStreamOpen = p;
    p = GetProcAddress(g_real_winmm, "midiStreamOut"); if (p) ptr_midiStreamOut = p;
    p = GetProcAddress(g_real_winmm, "midiStreamPause"); if (p) ptr_midiStreamPause = p;
    p = GetProcAddress(g_real_winmm, "midiStreamPosition"); if (p) ptr_midiStreamPosition = p;
    p = GetProcAddress(g_real_winmm, "midiStreamProperty"); if (p) ptr_midiStreamProperty = p;
    p = GetProcAddress(g_real_winmm, "midiStreamRestart"); if (p) ptr_midiStreamRestart = p;
    p = GetProcAddress(g_real_winmm, "midiStreamStop"); if (p) ptr_midiStreamStop = p;
    p = GetProcAddress(g_real_winmm, "mixerClose"); if (p) ptr_mixerClose = p;
    p = GetProcAddress(g_real_winmm, "mixerGetControlDetailsA"); if (p) ptr_mixerGetControlDetailsA = p;
    p = GetProcAddress(g_real_winmm, "mixerGetControlDetailsW"); if (p) ptr_mixerGetControlDetailsW = p;
    p = GetProcAddress(g_real_winmm, "mixerGetDevCapsA"); if (p) ptr_mixerGetDevCapsA = p;
    p = GetProcAddress(g_real_winmm, "mixerGetDevCapsW"); if (p) ptr_mixerGetDevCapsW = p;
    p = GetProcAddress(g_real_winmm, "mixerGetID"); if (p) ptr_mixerGetID = p;
    p = GetProcAddress(g_real_winmm, "mixerGetLineControlsA"); if (p) ptr_mixerGetLineControlsA = p;
    p = GetProcAddress(g_real_winmm, "mixerGetLineControlsW"); if (p) ptr_mixerGetLineControlsW = p;
    p = GetProcAddress(g_real_winmm, "mixerGetLineInfoA"); if (p) ptr_mixerGetLineInfoA = p;
    p = GetProcAddress(g_real_winmm, "mixerGetLineInfoW"); if (p) ptr_mixerGetLineInfoW = p;
    p = GetProcAddress(g_real_winmm, "mixerGetNumDevs"); if (p) ptr_mixerGetNumDevs = p;
    p = GetProcAddress(g_real_winmm, "mixerMessage"); if (p) ptr_mixerMessage = p;
    p = GetProcAddress(g_real_winmm, "mixerOpen"); if (p) ptr_mixerOpen = p;
    p = GetProcAddress(g_real_winmm, "mixerSetControlDetails"); if (p) ptr_mixerSetControlDetails = p;
    p = GetProcAddress(g_real_winmm, "mmDrvInstall"); if (p) ptr_mmDrvInstall = p;
    p = GetProcAddress(g_real_winmm, "mmGetCurrentTask"); if (p) ptr_mmGetCurrentTask = p;
    p = GetProcAddress(g_real_winmm, "mmioAdvance"); if (p) ptr_mmioAdvance = p;
    p = GetProcAddress(g_real_winmm, "mmioAscend"); if (p) ptr_mmioAscend = p;
    p = GetProcAddress(g_real_winmm, "mmioClose"); if (p) ptr_mmioClose = p;
    p = GetProcAddress(g_real_winmm, "mmioCreateChunk"); if (p) ptr_mmioCreateChunk = p;
    p = GetProcAddress(g_real_winmm, "mmioDescend"); if (p) ptr_mmioDescend = p;
    p = GetProcAddress(g_real_winmm, "mmioFlush"); if (p) ptr_mmioFlush = p;
    p = GetProcAddress(g_real_winmm, "mmioGetInfo"); if (p) ptr_mmioGetInfo = p;
    p = GetProcAddress(g_real_winmm, "mmioInstallIOProcA"); if (p) ptr_mmioInstallIOProcA = p;
    p = GetProcAddress(g_real_winmm, "mmioInstallIOProcW"); if (p) ptr_mmioInstallIOProcW = p;
    p = GetProcAddress(g_real_winmm, "mmioOpenA"); if (p) ptr_mmioOpenA = p;
    p = GetProcAddress(g_real_winmm, "mmioOpenW"); if (p) ptr_mmioOpenW = p;
    p = GetProcAddress(g_real_winmm, "mmioRead"); if (p) ptr_mmioRead = p;
    p = GetProcAddress(g_real_winmm, "mmioRenameA"); if (p) ptr_mmioRenameA = p;
    p = GetProcAddress(g_real_winmm, "mmioRenameW"); if (p) ptr_mmioRenameW = p;
    p = GetProcAddress(g_real_winmm, "mmioSeek"); if (p) ptr_mmioSeek = p;
    p = GetProcAddress(g_real_winmm, "mmioSendMessage"); if (p) ptr_mmioSendMessage = p;
    p = GetProcAddress(g_real_winmm, "mmioSetBuffer"); if (p) ptr_mmioSetBuffer = p;
    p = GetProcAddress(g_real_winmm, "mmioSetInfo"); if (p) ptr_mmioSetInfo = p;
    p = GetProcAddress(g_real_winmm, "mmioStringToFOURCCA"); if (p) ptr_mmioStringToFOURCCA = p;
    p = GetProcAddress(g_real_winmm, "mmioStringToFOURCCW"); if (p) ptr_mmioStringToFOURCCW = p;
    p = GetProcAddress(g_real_winmm, "mmioWrite"); if (p) ptr_mmioWrite = p;
    p = GetProcAddress(g_real_winmm, "mmsystemGetVersion"); if (p) ptr_mmsystemGetVersion = p;
    p = GetProcAddress(g_real_winmm, "mmTaskBlock"); if (p) ptr_mmTaskBlock = p;
    p = GetProcAddress(g_real_winmm, "mmTaskCreate"); if (p) ptr_mmTaskCreate = p;
    p = GetProcAddress(g_real_winmm, "mmTaskSignal"); if (p) ptr_mmTaskSignal = p;
    p = GetProcAddress(g_real_winmm, "mmTaskYield"); if (p) ptr_mmTaskYield = p;
    p = GetProcAddress(g_real_winmm, "OpenDriver"); if (p) ptr_OpenDriver = p;
    p = GetProcAddress(g_real_winmm, "PlaySound"); if (p) ptr_PlaySound = p;
    p = GetProcAddress(g_real_winmm, "PlaySoundA"); if (p) ptr_PlaySoundA = p;
    p = GetProcAddress(g_real_winmm, "PlaySoundW"); if (p) ptr_PlaySoundW = p;
    p = GetProcAddress(g_real_winmm, "SendDriverMessage"); if (p) ptr_SendDriverMessage = p;
    p = GetProcAddress(g_real_winmm, "sndPlaySoundA"); if (p) ptr_sndPlaySoundA = p;
    p = GetProcAddress(g_real_winmm, "sndPlaySoundW"); if (p) ptr_sndPlaySoundW = p;
    p = GetProcAddress(g_real_winmm, "timeBeginPeriod"); if (p) ptr_timeBeginPeriod = p;
    p = GetProcAddress(g_real_winmm, "timeEndPeriod"); if (p) ptr_timeEndPeriod = p;
    p = GetProcAddress(g_real_winmm, "timeGetDevCaps"); if (p) ptr_timeGetDevCaps = p;
    p = GetProcAddress(g_real_winmm, "timeGetSystemTime"); if (p) ptr_timeGetSystemTime = p;
    p = GetProcAddress(g_real_winmm, "timeGetTime"); if (p) ptr_timeGetTime = p;
    p = GetProcAddress(g_real_winmm, "timeKillEvent"); if (p) ptr_timeKillEvent = p;
    p = GetProcAddress(g_real_winmm, "timeSetEvent"); if (p) ptr_timeSetEvent = p;
    p = GetProcAddress(g_real_winmm, "waveInAddBuffer"); if (p) ptr_waveInAddBuffer = p;
    p = GetProcAddress(g_real_winmm, "waveInClose"); if (p) ptr_waveInClose = p;
    p = GetProcAddress(g_real_winmm, "waveInGetDevCapsA"); if (p) ptr_waveInGetDevCapsA = p;
    p = GetProcAddress(g_real_winmm, "waveInGetDevCapsW"); if (p) ptr_waveInGetDevCapsW = p;
    p = GetProcAddress(g_real_winmm, "waveInGetErrorTextA"); if (p) ptr_waveInGetErrorTextA = p;
    p = GetProcAddress(g_real_winmm, "waveInGetErrorTextW"); if (p) ptr_waveInGetErrorTextW = p;
    p = GetProcAddress(g_real_winmm, "waveInGetID"); if (p) ptr_waveInGetID = p;
    p = GetProcAddress(g_real_winmm, "waveInGetNumDevs"); if (p) ptr_waveInGetNumDevs = p;
    p = GetProcAddress(g_real_winmm, "waveInGetPosition"); if (p) ptr_waveInGetPosition = p;
    p = GetProcAddress(g_real_winmm, "waveInMessage"); if (p) ptr_waveInMessage = p;
    p = GetProcAddress(g_real_winmm, "waveInOpen"); if (p) ptr_waveInOpen = p;
    p = GetProcAddress(g_real_winmm, "waveInPrepareHeader"); if (p) ptr_waveInPrepareHeader = p;
    p = GetProcAddress(g_real_winmm, "waveInReset"); if (p) ptr_waveInReset = p;
    p = GetProcAddress(g_real_winmm, "waveInStart"); if (p) ptr_waveInStart = p;
    p = GetProcAddress(g_real_winmm, "waveInStop"); if (p) ptr_waveInStop = p;
    p = GetProcAddress(g_real_winmm, "waveInUnprepareHeader"); if (p) ptr_waveInUnprepareHeader = p;
    p = GetProcAddress(g_real_winmm, "waveOutBreakLoop"); if (p) ptr_waveOutBreakLoop = p;
    p = GetProcAddress(g_real_winmm, "waveOutClose"); if (p) ptr_waveOutClose = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetDevCapsA"); if (p) ptr_waveOutGetDevCapsA = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetDevCapsW"); if (p) ptr_waveOutGetDevCapsW = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetErrorTextA"); if (p) ptr_waveOutGetErrorTextA = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetErrorTextW"); if (p) ptr_waveOutGetErrorTextW = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetID"); if (p) ptr_waveOutGetID = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetNumDevs"); if (p) ptr_waveOutGetNumDevs = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetPitch"); if (p) ptr_waveOutGetPitch = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetPlaybackRate"); if (p) ptr_waveOutGetPlaybackRate = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetPosition"); if (p) ptr_waveOutGetPosition = p;
    p = GetProcAddress(g_real_winmm, "waveOutGetVolume"); if (p) ptr_waveOutGetVolume = p;
    p = GetProcAddress(g_real_winmm, "waveOutMessage"); if (p) ptr_waveOutMessage = p;
    p = GetProcAddress(g_real_winmm, "waveOutOpen"); if (p) ptr_waveOutOpen = p;
    p = GetProcAddress(g_real_winmm, "waveOutPause"); if (p) ptr_waveOutPause = p;
    p = GetProcAddress(g_real_winmm, "waveOutPrepareHeader"); if (p) ptr_waveOutPrepareHeader = p;
    p = GetProcAddress(g_real_winmm, "waveOutReset"); if (p) ptr_waveOutReset = p;
    p = GetProcAddress(g_real_winmm, "waveOutRestart"); if (p) ptr_waveOutRestart = p;
    p = GetProcAddress(g_real_winmm, "waveOutSetPitch"); if (p) ptr_waveOutSetPitch = p;
    p = GetProcAddress(g_real_winmm, "waveOutSetPlaybackRate"); if (p) ptr_waveOutSetPlaybackRate = p;
    p = GetProcAddress(g_real_winmm, "waveOutSetVolume"); if (p) ptr_waveOutSetVolume = p;
    p = GetProcAddress(g_real_winmm, "waveOutUnprepareHeader"); if (p) ptr_waveOutUnprepareHeader = p;
    p = GetProcAddress(g_real_winmm, "waveOutWrite"); if (p) ptr_waveOutWrite = p;
    p = GetProcAddress(g_real_winmm, "WOWAppExit"); if (p) ptr_WOWAppExit = p;
}

